import os
import urllib.parse

DEFAULT_USER = ''
DEFAULT_PWD = ''
DEFAULT_HOST = ''
DEFAULT_PORT = ''

DEFAULT_PWD_ENCODED = urllib.parse.quote_plus(DEFAULT_PWD)

VISIONA_DATABASE = os.environ.get('VISIONA_DATABASE', '')

VISIONA_DB_SCHEMA = f"{VISIONA_DATABASE}.{os.environ.get('VISIONA_DB_SCHEMA', 'public')}"

VISIONA_DATABASE_URL = os.environ.get(
    'MIDALL_DATABASE_URL',
    f'mysql+pymysql://{DEFAULT_USER}:{DEFAULT_PWD_ENCODED}@{DEFAULT_HOST}:{DEFAULT_PORT}/{VISIONA_DATABASE}'
)

SQLALCHEMY_TRACK_MODIFICATIONS = int(os.environ.get('SQLALCHEMY_TRACK_MODIFICATIONS', '0')) == 1
SQLALCHEMY_ECHO = int(os.environ.get('SQLALCHEMY_ECHO', '0')) == 1