import flaskr.config_app as ca
from flaskr.db import db_instance

class Saida5Model(db_instance.Model):
    __tablename__ = 'saida5'
    __table__args__ = {"schema": ca.VISIONA_DB_SCHEMA}

    ref_bacen = db_instance.Column(db_instance.String(100))
    nu_ordem = db_instance.Column(db_instance.String(100))
    cnpj_if = db_instance.Column(db_instance.String(100))
    dt_emissao = db_instance.Column(db_instance.String(100))
    dt_vencimento = db_instance.Column(db_instance.String(100))
    cd_inst_credito = db_instance.Column(db_instance.String(100))
    cd_categ_emitente = db_instance.Column(db_instance.String(100))
    cd_fonte_recurso = db_instance.Column(db_instance.String(100))
    cnjp_agente_invest = db_instance.Column(db_instance.String(100))
    cd_estado = db_instance.Column(db_instance.String(100))
    cd_ref_bacen_investimento = db_instance.Column(db_instance.String(100))
    cd_tipo_seguro = db_instance.Column(db_instance.String(100))
    cd_empreendimento = db_instance.Column(db_instance.String(100))
    cd_programa = db_instance.Column(db_instance.String(100))
    cd_tipo_encarg_financ = db_instance.Column(db_instance.String(100))
    cd_tipo_irrigacao = db_instance.Column(db_instance.String(100))
    cd_tipo_agricultura = db_instance.Column(db_instance.String(100))
    cd_fase_ciclo_producao = db_instance.Column(db_instance.String(100))
    cd_tipo_cultivo = db_instance.Column(db_instance.String(100))
    cd_tipo_intgr_consor = db_instance.Column(db_instance.String(100))
    cd_tipo_grao_semente = db_instance.Column(db_instance.String(100))
    vl_aliq_proagro = db_instance.Column(db_instance.String(100))
    vl_juros = db_instance.Column(db_instance.String(100))
    vl_prestacao_investimento = db_instance.Column(db_instance.String(100))
    vl_prev_prod = db_instance.Column(db_instance.String(100))
    vl_quantidade = db_instance.Column(db_instance.String(100))
    vl_receita_bruta_esperada = db_instance.Column(db_instance.String(100))
    vl_parc_credito = db_instance.Column(db_instance.String(100))
    vl_rec_proprio = db_instance.Column(db_instance.String(100))
    vl_perc_risco_stn = db_instance.Column(db_instance.String(100))
    vl_perc_risco_fundo_const = db_instance.Column(db_instance.String(100))
    vl_rec_proprio_srv = db_instance.Column(db_instance.String(100))
    vl_area_financ = db_instance.Column(db_instance.String(100))
    cd_subprograma = db_instance.Column(db_instance.String(100))
    vl_produtiv_obtida = db_instance.Column(db_instance.String(100))
    dt_fim_colheita = db_instance.Column(db_instance.String(100))
    dt_fim_plantio = db_instance.Column(db_instance.String(100))
    dt_inic_colheita = db_instance.Column(db_instance.String(100))
    dt_inic_plantio = db_instance.Column(db_instance.String(100))
    vl_juros_enc_finac_posfix = db_instance.Column(db_instance.String(100))
    vl_perc_custo_efet_total = db_instance.Column(db_instance.String(100))
    cd_contrato_stn = db_instance.Column(db_instance.String(100))                                 